simulator:
  service_type: example_simulator
  requires_safety: false

zernike_dm:
  service_type: empty_service
  simulated_service_type: zernike_dm_sim
  requires_safety: false

  number_modes: 10

detector:
  service_type: allied_vision_camera
  simulated_service_type: camera_sim
  interface: camera
  requires_safety: false

  camera_id: "DEV_1AB22C054FE7"
  device_name: Allied Alvium 1800 U-040m
  pixel_format: Mono8

  offset_x: 0
  offset_y: 0
  width: 728
  height: 544
  sensor_width: 728
  sensor_height: 544
  exposure_time: 400
  gain: 0

  bit_saturation: 8